sudo: false
language: go
go:
  - 1.7
  - 1.8
  - 1.8.1
  - 1.8.2
  - 1.8.3
before_install:
  - go get -t -v ./...
  - go get github.com/mattn/goveralls
script:
  - go test -coverprofile=cookiesession.coverprofile
  - goveralls -coverprofile=cookiesession.coverprofile -service=travis-ci